### ISSUE TITLE
sublists ?

### ISSUE THREAD

**Issue by anjoweichbrodt** [opengisch/avenches#13]
Ist es möglich Unterlisten zu erstellen sowie :
listes.designation.etat ?
also eine Liste die nur Auswahlinformationen enthält die für die Gruppe "état" relevant sind ?

siehe den ergänzten Listen iin schema.sql

**Comment by m-kuhn** [comment]
Man kann einfach zwei Spalten in der Liste machen

| ID | Type | Definition |
| --- | --- | --- |
| 1 | etat | écaillage |
| 2 | etat | fissure |
| 3 | intervention | comblement |
