### ISSUE TITLE
Control layer visibility in map themes by expression

### ISSUE THREAD

**Issue by anjoweichbrodt** [opengisch/avenches#20]
It should be possible to control all layer's visibility by an expression defined on the map theme.

E.g.

    @layer_name = @atlas_feature

**Comment by m-kuhn** [comment]
Umsetzung über bestehende Möglichkeiten via Layernamen.

**Comment by anjoweichbrodt** [comment]
Umsetztung durch Expressions im Composer, Item properties - Layers:
`attribute(get_feature('fotos_before', 'surface',"name"),'filename')`
![image](https://user-images.githubusercontent.com/10090524/48255007-c541d800-e40b-11e8-819d-898ffb74e80d.png)

siehe auch #6
