### ISSUE TITLE
Quick Attribution Plugin auf QGIS 3 updaten

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/avenches#34]

**Comment by anjoweichbrodt** [comment]
QA-Plugin on surface_create (tested with QGIS v. 3.1.0_master.r47090.d87f75aa98-1):
- When adding a non existing _mur_ (i.e. M300) QGIS crashes. Should _murs_ be inserted in the table first?
- Cannot define _nomatlas_ manually  currently available values come form the import file: _surface_. I imagine a good solution would be that a name proposition for _nomatlas_ is created from exposition, mur and _sector_.  (i.ex. N + M10 +Cu2 -> M10-N_Cu2) But ideally the name could than be adapted.

**Comment by anjoweichbrodt** [comment]
Update wurde von @m-kuhn durchgeführt
