### ISSUE TITLE
Implementierung Datenmodell TRA in PgModeler

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/avenches#35]
Analog zu Orbe

Ist momentan als schema.sql (o.Ä.) abgelegt. Dieses soll durch ein PgModeler Modell abgelöst werden und entsprechend Mehrsprachig gehalten werden (wie Orbe eben).

**Comment by anjoweichbrodt** [comment]
Nicht mehr notwendig.

**Comment by anjoweichbrodt** [comment]
Nicht mehr notwendig.
