### ISSUE TITLE
Zugehöriges Mauerstück kann nicht ausgewählt werden beim Erfassen einer Surface

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/avenches#37]
Dropdown Button fehlt, Feld nicht editierbar. Feld ist als Relation Reference Widget konfiguiert.

In QGIS 2.18.16, sowie QGIS 3.0.0 reproduziert. QGIS Bug?

**Comment by m-kuhn** [comment]
Sollte inzwischen gelöst sein. @anjoweichbrodt kannst du das verifizieren und diesen Issue falls gelöst schliessen?

**Comment by anjoweichbrodt** [comment]
Hoi Matthias,

Ich schaue heut morgen gleich mal.

Lg,
Anjo

**Comment by anjoweichbrodt** [comment]
Super funtioniert @m-kuhn.
Fixes #37
