### ISSUE TITLE
Tabelle für Photos

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/avenches#6]
- FK Surface
- Dateiname (chemin_accès)
- Datum (Aufnahme) date_prise
- Datum (Erfassen) date_saisie

**Comment by m-kuhn** [comment]
Im Rahmen von #35 (Neuimplementation in PgModeler) nochmal anschauen.

**Comment by anjoweichbrodt** [comment]
Ist angepasst.
Lösung mit 2 Tabellen: fotos_before, fotos_after wurde umgesetzt um den Darstellungsfilter mittels Expressions im Composer nutzten zu können.
