### ISSUE TITLE
Mauern import

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/avenches#7]
Import CSV Datei

**Comment by anjoweichbrodt** [comment]
Is it possible that 1 "mur" relates to 2 "secteur"?

**Comment by m-kuhn** [comment]
Momentan nicht, 1 "secteur" hat n "mur"s, aber 1 "mur" gehört immer zu genau einem "secteur"

**Comment by m-kuhn** [comment]
Um die Mauern zu importieren brauchen wir zuerst alle [Sektoren](https://github.com/opengisch/avenches/blob/master/site_secteur.csv), wobei diese wiederum alle einem Monument zugeordnet sein müssen. Welchem Monument sind die Sektoren zugeordnet?

Ebenfalls bzgl. Sektoren, sind die Geometrien bereits vorhanden oder müssen diese noch gezeichent werden?

**Comment by m-kuhn** [comment]
N:M Beziehung Mur <-> Secteur
(Eine Mauer kann zu mehreren Sektoren gehören)

Dafür werden surfaces auch noch secteurs zugeordnet.
